### PR TITLE
Make question list look nicer

### PR DESCRIPTION
**Pull request by stephenjust**
This makes the question list properly populate from the top of the screen.

### CODE REVIEW

**Comment by sdwowk** [comment]
does it break sort?

**Comment by stephenjust** [comment]
I haven't checked, but this was just a layout change - no reason it would
interfere with code

**Comment by sdwowk** [comment]
It should be fine if it does, it would sort backwards, which is not a problem to fix

**Comment by lamorie** [comment]
Purely XML changes, seems safe to merge to me

**Pull request merged**
