### PR TITLE
Camera and Gallery, all local, only backend as the thumbnail is not currently working

### PR DESCRIPTION
**Pull request by lamorie**
Yes, it still needs tests

### CODE REVIEW

**Comment by Cotto4** [comment]
Seems reasonable to me, but Travis hates it. Any ideas anybody?

**Comment by stephenjust** [comment]
Travis is indicating that it can't find a class called AddImage. Are you missing a file?

**Comment by lamorie** [comment]
I'll look into it when I get home

**Comment by lamorie** [comment]
There we go, Now Travis is happy.

**Comment by linster** [comment]
Yay! We should all buy Travis a beer after exams ^_^

**Comment by lamorie** [comment]
no, we should all buy ourselves beer!

**Pull request merged**
