### PR TITLE
Attempted to add read later button to question list.

### PR DESCRIPTION
**Pull request by RyanKusters**
Needs layout adaptation for visual appeal.
Attempted to adapt client data store for persistance, though is buggy and
while i have not nailed dow the issue I do find persistance leaks.

Still working on it, when fixed, will add to Answer List and to comment list.

### CODE REVIEW

**Comment by RyanKusters** [comment]
this is operational, will need to amend it after merging

**Comment by stephenjust** [comment]
Ryan, can you merge from upstream and try to resolve conflicts?

With ClientData no longer being delegated to by DataManager, I think it might be worthwhile to have the following:

``` java
class ClientData {
    private static final String FAVORITE_LIST = "favorite";
    private static final String READ_LATER_LIST = "readLater";
    ...
    public void setFavoriteList(List<UUID> list) {
        setList(list, FAVORITE_LIST);
    }

    public void setReadLaterList(List<UUID> list) {
        setList(list, READ_LATER_LIST);
    }

    private void setList(List<UUID> list, String listName) { ... }
    ...
}
```

This means that you can share the common implementation of the two nearly identical functions in `setList`, but hide the magic constants from users of the class with the methods `setFavoriteList` and `setReadLaterList`.

**Comment by RyanKusters** [comment]
Ok I have solved the conflicts. what am I missing?

**Comment by RyanKusters** [comment]
tested, operational

**Comment by stephenjust** [comment]
Not totally sure what happened with the merge, but I can handle that if someone else reviews.
@Kopo101 or @linster or @sdwowk or @lamorie ?

**Comment by linster** [comment]
As long as the rest of the app still works, it looks good.

**Pull request merged**
