### PR TITLE
I am being harrased, please ask the machine to stop.

### PR DESCRIPTION
**Pull request by RyanKusters**

### CODE REVIEW

**Comment by stephenjust** [comment]
A little messy, but whatever. If Travis passes, Approved.

**Comment by Cotto4** [comment]
Love it bb

**Comment by linster** [comment]
There were line deletions. We should be focusing on growing the product.

**Comment by lamorie** [comment]
My name is Brittany and I approve this message ;)

**Comment by RyanKusters** [comment]
post the file and line number and I will fix the indentation!

**Comment by Cotto4** [comment]
^

**Comment by Cotto4** [comment]
INDENTATION MEETING

**Comment by linster** [comment]
We need a Product Indentation Standards meeting. http://doodle.com/kypzs4qg46vwwem6

**Pull request merged**
