### PR TITLE
Tc13- Authenticate the user

### PR DESCRIPTION
**Pull request by sdwowk**
Please review!!

### CODE REVIEW

**Comment by stephenjust** [comment]
Looks fine to me.

**Comment by Cotto4** [comment]
Love it

**Comment by sdwowk** [comment]
If we are adding questions to the DataManager and the Question class does not have access to the DataManager's methods how does it get the author? (If the authorship is stored in the local data store)

**Comment by stephenjust** [comment]
@sdwowk: There are a few options:
- the location of the user account could be changed
- questions, answers, and comments could be created by some factory that does have access to this data
- give the items access to DataManager
- others I haven't thought of

This is something we'd have to change near the beginning of Milestone 3. Maybe add a ticket for figuring that out.

**Comment by sdwowk** [comment]
Could we pas in the DataManager when we create a question?

**Comment by stephenjust** [comment]
With DataManager being a singleton, that's pretty unnecessary. If question
wants it, it can just do "DataManger.getInstance().doWhatever()"

## 

Stephen Just

**Pull request merged**
