### PR TITLE
comments now show newest first

### PR DESCRIPTION
**Pull request by Cotto4**
Quickest fix evaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa. I'm tired.

### CODE REVIEW

**Comment by stephenjust** [comment]
Uh... http://developer.android.com/reference/android/widget/ArrayAdapter.html#sort(java.util.Comparator<? super T>)

**Comment by RyanKusters** [comment]
Which means please implement a sort comparator cause ES is silly, this fix wont work.

**Comment by Cotto4** [comment]
Ah damn. I'll revisit it in a bit

**Comment by Cotto4** [comment]
Fixed. It works now I swear >.<

**Comment by linster** [comment]
@Kopo101 , I'ma take your word for it.

**Pull request merged**
