### PR TITLE
Some work towards LocalDataManager: ClientData class

### PR DESCRIPTION
**Pull request by stephenjust**
As part of working on LocalDataManager, I split off the username stuff into a separate class. (Favorite and ReadLater ID's would go in this new class too eventually.)

SharedPreferences needs a Context, so DataManager also needs a Context. So the tests also need to provide a context. I've taken care of all of that so that project and tests all compile again.

I would highly recommend that this is reviewed quickly, and that everyone rebase off of this before doing further code because it will cause headaches otherwise.

### CODE REVIEW

**Comment by sdwowk** [comment]
Will local data store save client data? Code looks good to me.

**Comment by stephenjust** [comment]
The idea is that *DataStore will store Questions, Answers, Comments, whereas ClientData stores things like Username, Favorite list, ReadLater list. *DataStore does not talk directly to ClientData, as it is not suitable for storing such complex data.

**Comment by Cotto4** [comment]
Looks solid to me, the UUID changes are pretty important I think. I'm too tired to go through and make sure you didn't miss any, and if we come across them we can always fix it later. Client data is also a good idea, even though we have no user account it is useful to store account-like things. Client data is local data, but not managed by localdatastore right?

**Comment by stephenjust** [comment]
That's right.

**Comment by Cotto4** [comment]
Perfect, merged in then.

**Pull request merged**
